### ISSUE TITLE
Jumping equipnement on field

### ISSUE THREAD

**Issue by xxx514** [900hasse/FS22_REAcog#14]
Hello!

Awesome mod, really nice addition of reality to game. Unfortunately, I've found something weird - trying to cultivate field makes cultivator shaking. Ground is properly changed, however it looks very strange and I afraid such behaviour may launch tractor into space or below ground (seen such bugs in few games :D ) Is it possible such behaviour is due to another mod - Mud System - making such giggles? Attaching a vid to let You see directly how it looks. https://youtu.be/OYJXDrLlSWY

Thanks for shareing time.

**Comment by Tubezki** [comment]
![Screenshot 2023-09-14 130358](https://github.com/900hasse/FS22_REAcog/assets/96207795/45c5394a-f5cd-467e-a30d-3944795f75f4)
This is caused by REAWheels. I have a fix for you, find this: local SidewayResistanceForceFactor 
and change the default number to local SidewayResistanceForceFactor = 0.2 

This will stop those implements to wiggling. But keeps small amount of sidewayResistanceForce...

**Comment by xxx514** [comment]
Weeee! Its working! No more suspicious giggling! Thanks a lot good sir!

**Comment by xxx514** [comment]
Weeee! Its working! No more suspicious giggling! Thanks a lot good sir!
